language: node_js
node_js:
  - 0.8
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
after_install:
  - "npm run-script install-selenium"
before_script:
  - "npm run-script kill-selenium"
  - "npm run-script start-selenium"
  - "sleep 20"
after_script:
  - "npm run-script kill-selenium"

