language: node_js
node_js:
  - 0.8
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
after_install:
  - "npm run-script install-selenium"
before_script:
  - "npm run-script kill-selenium"
  - "npm run-script start-selenium"
  - "sleep 20"
after_script:
  - "npm run-script kill_selenium"

