// Generated by CoffeeScript 1.3.3
(function() {
  var Soda, SodaCan, should, soda, someText, _ref;

  should = require('should');

  _ref = require('../../lib/soda-sync'), soda = _ref.soda, Soda = _ref.Soda, SodaCan = _ref.SodaCan;

  someText = null;

  describe("SodaCan", function() {
    var browser;
    browser = null;
    it("create client", function(done) {
      browser = soda.createClient({
        host: "localhost",
        port: 4444,
        url: "http://www.google.com",
        browser: "firefox",
        mode: 'sync'
      });
      return done();
    });
    describe("with soda can, passing browser", function() {
      return it("should work", SodaCan({
        "with": function() {
          return browser;
        },
        pre: function() {
          this.timeout(30000);
          return someText = 'Test1';
        }
      }, function() {
        someText.should.equal('Test1');
        this.session();
        this.open('/');
        this.getTitle().toLowerCase().should.include('google');
        return this.testComplete();
      }));
    });
    return describe("with soda can, without passing browser", function() {
      SodaCan = SodaCan({
        "with": function() {
          return browser;
        },
        pre: function() {
          this.timeout(30000);
          return someText = 'Test2';
        }
      });
      return it("should work", SodaCan(function() {
        someText.should.equal('Test2');
        this.session();
        this.open('/');
        this.getTitle().toLowerCase().should.include('google');
        return this.testComplete();
      }));
    });
  });

}).call(this);
