// Generated by CoffeeScript 1.4.0
(function() {
  var should, sodaSync;

  should = require('should');

  sodaSync = require('../../lib/soda-sync');

  describe("sync", function() {
    var browser, sync, _ref;
    _ref = {}, browser = _ref.browser, sync = _ref.sync;
    it("create client", function(done) {
      var _ref1;
      _ref1 = sodaSync.createClient({
        host: "localhost",
        port: 4444,
        url: "http://www.google.com",
        browser: "firefox"
      }), browser = _ref1.browser, sync = _ref1.sync;
      return done();
    });
    describe("step by step run", function() {
      it("open session", function(done) {
        return sync(function() {
          this.session();
          return done();
        });
      });
      it("opens page", function(done) {
        return sync(function() {
          this.open('/');
          return done();
        });
      });
      it("types something", function(done) {
        return sync(function() {
          this.type('q', 'Hello World');
          return done();
        });
      });
      it("clicks button", function(done) {
        return sync(function() {
          this.click('btnG');
          return done();
        });
      });
      it("waits", function(done) {
        return sync(function() {
          this.waitForElementPresent('css=#topstuff');
          return done();
        });
      });
      it("checks title", function(done) {
        return sync(function() {
          this.getTitle().toLowerCase().should.include('hello world');
          return done();
        });
      });
      return it("finishes test", function(done) {
        return sync(function() {
          this.testComplete();
          return done();
        });
      });
    });
    return describe("retrieving the current browser in an external function", function() {
      var myOwnGetTitle;
      myOwnGetTitle = function() {
        return sodaSync.current().getTitle();
      };
      return it("should work", function(done) {
        return sync(function() {
          this.session();
          this.open('/');
          myOwnGetTitle().toLowerCase().should.include('google');
          this.testComplete();
          return done();
        });
      });
    });
  });

}).call(this);
